import type { PublishPlatform, PublishSkill } from './types';

export const bossLikePublishSkill: PublishSkill = {
  id: 'boss-like-publish-jd',
  name: 'publish_jd',
  platform: 'boss-like',
  description: 'Publish a generated JD to the local boss-like employer job form.',
  version: 1,
  isActive: true,
  inputSchema: {
    title: 'string',
    company: 'string',
    salary: 'string',
    location: 'string',
    description: 'string',
    keywords: 'string[]',
  },
  variables: {},
  steps: [
    {
      id: 'open_new_job',
      type: 'action',
      action: 'navigate',
      params: { url: '{{target.newJobUrl}}' },
      next: 'check_login',
      onFail: { type: 'fallback_agent', reason: 'cannot open new job page' },
    },
    {
      id: 'check_login',
      type: 'condition',
      check: {
        id: 'new_job_form_visible',
        type: 'text_contains',
        text: '职位名称',
        timeout: 5_000,
      },
      ifTrue: { next: 'fill_title' },
      ifFalse: { next: 'fill_username' },
    },
    {
      id: 'fill_username',
      type: 'action',
      action: 'fill',
      params: { locator: '用户名', value: '{{credentials.username}}' },
      next: 'fill_password',
      onFail: { type: 'fallback_agent', reason: 'cannot fill username' },
    },
    {
      id: 'fill_password',
      type: 'action',
      action: 'fill',
      params: { locator: '密码', value: '{{credentials.password}}' },
      next: 'submit_login',
      onFail: { type: 'fallback_agent', reason: 'cannot fill password' },
    },
    {
      id: 'submit_login',
      type: 'action',
      action: 'click',
      params: { locator: '登录' },
      next: 'wait_after_login',
      onFail: { type: 'fallback_agent', reason: 'cannot submit login' },
    },
    {
      id: 'wait_after_login',
      type: 'action',
      action: 'wait_for_url',
      params: { url: '/employer/resumes' },
      next: 'open_new_job_after_login',
      onFail: { type: 'fallback_agent', reason: 'login redirect did not complete' },
    },
    {
      id: 'open_new_job_after_login',
      type: 'action',
      action: 'navigate',
      params: { url: '{{target.newJobUrl}}' },
      next: 'fill_title',
      onFail: { type: 'fallback_agent', reason: 'cannot open new job page after login' },
    },
    {
      id: 'fill_title',
      type: 'action',
      action: 'fill',
      params: { locator: '职位名称', value: '{{input.title}}' },
      next: 'fill_company',
      onFail: { type: 'fallback_agent', reason: 'cannot fill job title' },
    },
    {
      id: 'fill_company',
      type: 'action',
      action: 'fill',
      params: { locator: '公司名称', value: '{{input.company}}' },
      next: 'fill_salary',
      onFail: { type: 'fallback_agent', reason: 'cannot fill company name' },
    },
    {
      id: 'fill_salary',
      type: 'action',
      action: 'fill',
      params: { locator: '薪资范围', value: '{{input.salary}}' },
      next: 'fill_location',
      onFail: { type: 'fallback_agent', reason: 'cannot fill salary range' },
    },
    {
      id: 'fill_location',
      type: 'action',
      action: 'fill',
      params: { locator: '工作地点', value: '{{input.location}}' },
      next: 'fill_description',
      onFail: { type: 'fallback_agent', reason: 'cannot fill job location' },
    },
    {
      id: 'fill_description',
      type: 'action',
      action: 'fill',
      params: { locator: '职位描述', value: '{{input.description}}' },
      next: 'add_keywords',
      onFail: { type: 'fallback_agent', reason: 'cannot fill job description' },
    },
    {
      id: 'add_keywords',
      type: 'action',
      action: 'add_keywords',
      params: {
        locator: '技能标签',
        values: '{{input.keywords}}',
        submitLocator: '添加',
      },
      next: 'submit_job',
      onFail: { type: 'fallback_agent', reason: 'cannot add skill keywords' },
    },
    {
      id: 'submit_job',
      type: 'action',
      action: 'click',
      params: { locator: '发布职位' },
      next: 'wait_jobs_list',
      onFail: { type: 'fallback_agent', reason: 'cannot submit job publish form' },
    },
    {
      id: 'wait_jobs_list',
      type: 'action',
      action: 'wait_for_url',
      params: { url: '/employer/jobs' },
      next: 'verify_published',
      onFail: { type: 'fallback_agent', reason: 'jobs list redirect did not complete' },
    },
    {
      id: 'verify_published',
      type: 'condition',
      check: { id: 'job_title_visible', type: 'text_contains', text: '{{input.title}}' },
      ifTrue: { next: 'done' },
      onFail: { type: 'fallback_agent', reason: 'published job title is not visible' },
    },
    { id: 'done', type: 'end' },
    { id: 'failed', type: 'end' },
  ],
};

const activeSkills: Record<PublishPlatform, PublishSkill> = {
  'boss-like': bossLikePublishSkill,
};

export function getActivePublishSkill(platform: PublishPlatform): PublishSkill {
  return activeSkills[platform];
}
