CREATE TABLE `llm_call_logs` (
  `id` VARCHAR(36) NOT NULL,
  `call_id` VARCHAR(128) NULL,
  `trace_id` VARCHAR(128) NULL,
  `request_id` VARCHAR(128) NULL,
  `endpoint` VARCHAR(128) NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `model` VARCHAR(128) NOT NULL,
  `request_headers` JSON NOT NULL,
  `request_payload` JSON NOT NULL,
  `response_payload` JSON NULL,
  `input_tokens` INTEGER NOT NULL,
  `output_tokens` INTEGER NOT NULL,
  `total_tokens` INTEGER NOT NULL,
  `latency_ms` INTEGER NOT NULL,
  `http_status` INTEGER NULL,
  `is_error` BOOLEAN NOT NULL DEFAULT false,
  `error_domain` VARCHAR(64) NULL,
  `error_code` VARCHAR(128) NULL,
  `provider_status` VARCHAR(128) NULL,
  `retry_count` INTEGER NOT NULL DEFAULT 0,
  `final_outcome` VARCHAR(32) NOT NULL,
  `timestamp` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `llm_call_logs_call_id_key` (`call_id`),
  UNIQUE INDEX `llm_call_logs_provider_request_id_key` (`provider`, `request_id`),
  INDEX `idx_llm_call_logs_timestamp` (`timestamp`),
  INDEX `idx_llm_call_logs_is_error_timestamp` (`is_error`, `timestamp`),
  INDEX `idx_llm_call_logs_provider_model_timestamp` (`provider`, `model`, `timestamp`),
  INDEX `idx_llm_call_logs_endpoint_timestamp` (`endpoint`, `timestamp`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `llm_usage_stats_daily` (
  `id` VARCHAR(36) NOT NULL,
  `bucket_date` DATE NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `model` VARCHAR(128) NOT NULL,
  `endpoint` VARCHAR(128) NOT NULL,
  `total_calls` INTEGER NOT NULL DEFAULT 0,
  `success_calls` INTEGER NOT NULL DEFAULT 0,
  `error_calls` INTEGER NOT NULL DEFAULT 0,
  `input_tokens` INTEGER NOT NULL DEFAULT 0,
  `output_tokens` INTEGER NOT NULL DEFAULT 0,
  `total_tokens` INTEGER NOT NULL DEFAULT 0,
  `avg_latency_ms` DOUBLE NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `llm_usage_stats_daily_bucket_provider_model_endpoint_key` (`bucket_date`, `provider`, `model`, `endpoint`),
  INDEX `idx_llm_usage_stats_daily_bucket_date` (`bucket_date`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `llm_usage_stats_weekly` (
  `id` VARCHAR(36) NOT NULL,
  `bucket_week` DATE NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `model` VARCHAR(128) NOT NULL,
  `endpoint` VARCHAR(128) NOT NULL,
  `total_calls` INTEGER NOT NULL DEFAULT 0,
  `success_calls` INTEGER NOT NULL DEFAULT 0,
  `error_calls` INTEGER NOT NULL DEFAULT 0,
  `input_tokens` INTEGER NOT NULL DEFAULT 0,
  `output_tokens` INTEGER NOT NULL DEFAULT 0,
  `total_tokens` INTEGER NOT NULL DEFAULT 0,
  `avg_latency_ms` DOUBLE NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `llm_usage_stats_weekly_bucket_provider_model_endpoint_key` (`bucket_week`, `provider`, `model`, `endpoint`),
  INDEX `idx_llm_usage_stats_weekly_bucket_week` (`bucket_week`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `llm_usage_stats_total` (
  `id` VARCHAR(36) NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `model` VARCHAR(128) NOT NULL,
  `endpoint` VARCHAR(128) NOT NULL,
  `total_calls` INTEGER NOT NULL DEFAULT 0,
  `success_calls` INTEGER NOT NULL DEFAULT 0,
  `error_calls` INTEGER NOT NULL DEFAULT 0,
  `input_tokens` INTEGER NOT NULL DEFAULT 0,
  `output_tokens` INTEGER NOT NULL DEFAULT 0,
  `total_tokens` INTEGER NOT NULL DEFAULT 0,
  `avg_latency_ms` DOUBLE NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `llm_usage_stats_total_provider_model_endpoint_key` (`provider`, `model`, `endpoint`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
