export const WORKFLOW_AGENT_MAX_STEPS = 15;
export const WORKFLOW_PLAYWRIGHT_TIMEOUT_MS = 30_000;
export const WORKFLOW_TOOL_RESULT_MAX_CHARS = 8_000;
export const BROWSER_SESSION_IDLE_TIMEOUT_MS = 300_000;
export const BROWSER_WAIT_POLL_INTERVAL_MS = 2_000;
export const BROWSER_WAIT_DEFAULT_TIMEOUT_MS = 120_000;
